CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes --convergence_thr=30 --convergence_thr_shape=50
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_obsestdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=randn_sequential_onlymlp_enc1dec0_woFix --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=randn_sequential_encoder_enc3dec0_Fix --N_batch=8   --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=randn_sequential_encoder_enc3dec0_Fix --N_batch=8   --val_model_epoch=272
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc3dec0_woFix --N_batch=8 --total_itr=10 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix   --N_batch=8 --total_itr=10 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc3dec0_woFix --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix   --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc3dec0_woFix --N_batch=8 --val_model_epoch=408
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix   --N_batch=8 --val_model_epoch=408
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix   --N_batch=8 --val_model_epoch=336