CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01 --N_batch=3 --val_model_epoch=800 --total_itr=5
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=6 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=10 --add_conf=T_Fixup --val_model_epoch=800 --num_workers=8
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix --N_batch=3 --val_model_epoch=400

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=3 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=792 --until_convergence=yes --convergence_thr=3 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau02 --N_batch=15 --val_model_epoch=752 --until_convergence=yes --convergence_thr=3 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=3 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=792
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=792 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=792 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=30

# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau02 --N_batch=15 --val_model_epoch=752
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau02 --N_batch=15 --val_model_epoch=752 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=30
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=696 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=10 --convergence_thr_shape=35
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=696
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau02 --N_batch=15 --val_model_epoch=752 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=30
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=696 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=30
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=10 --convergence_thr_shape=35
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=15 --val_model_epoch=936
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=20
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01 --N_batch=15 --val_model_epoch=800 --until_convergence=yes --convergence_thr=5 --convergence_thr_shape=30
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=15 --val_model_epoch=696 --until_convergence=yes --convergence_thr=10 --convergence_thr_shape=35
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau02 --N_batch=15 --val_model_epoch=752 --until_convergence=yes --convergence_thr=10 --convergence_thr_shape=35