# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_onlymlp_tau00 --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --total_itr=10 --itr_per_frame=2
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=10 --itr_per_frame=2 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_autoreg_tau01 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --itr_per_frame=2 --add_conf=T_Fixup --val_model_epoch=216
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq_encoder_tau00     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_autoreg_tau01_FINETUNE_0525 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=25 --itr_per_frame=5 --add_conf=T_Fixup --val_model_epoch=160 --fine_tune=yes
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_autoreg_tau01_FINETUNE_0315 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=15 --itr_per_frame=3 --add_conf=T_Fixup --val_model_epoch=160 --fine_tune=yes
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_autoreg_tau01padsrc         --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --itr_per_frame=2 --add_conf=T_Fixup
CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0210_autoreg_tau01padmlp         --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --itr_per_frame=2 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0315_onlymlp_tau00 --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --total_itr=15 --itr_per_frame=3
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0315_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=15 --itr_per_frame=3 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq0315_autoreg_tau01 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=15 --itr_per_frame=3 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01img  --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --add_conf=T_Fixup
 
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau01 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=10 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_autoreg_tau02 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --add_conf=T_Fixup --inp_itr_num=2
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=subrndnsim_onlymlp_tau00 --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --total_itr=10
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=prgrndnsim_autoreg_tau01 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=prgrndnsim_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=10 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=prgrndnsim_autoreg_tau02 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=10 --add_conf=T_Fixup --inp_itr_num=2
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=prgrndnsim_onlymlp_tau00 --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --total_itr=10
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq_autoreg_tau01 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=25 --itr_per_frame=5 --add_conf=T_Fixup --dec_inp_type=dif_obs
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=25 --itr_per_frame=5 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq_autoreg_tau02 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --total_itr=25 --itr_per_frame=5 --add_conf=T_Fixup --dec_inp_type=dif_obs --inp_itr_num=2
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=subcontseq_onlymlp_tau00 --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --total_itr=25 --itr_per_frame=5
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=tes05_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=5 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=tes01_encoder_tau00 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --total_itr=1 --add_conf=T_Fixup


# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=tes --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup --total_itr=25 --itr_per_frame=5 --save_interval=1
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=FINE_TUNE_autoreg_enc3dec3_Fix                                    --N_batch=32 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup --N_epoch=102 --total_itr=8 --val_model_epoch=400 --fine_tune=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix              --N_batch=8 --val_model_epoch=400 --total_itr=7 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=FINE_TUNE_encoder_enc3dec0_Fix                                    --N_batch=32 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --N_epoch=102 --total_itr=8 --val_model_epoch=400 --fine_tune=yes
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=400 --total_itr=7 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=FINE_TUNE_autoreg_enc3dec3_Fix_itr02_obsdif                       --N_batch=32 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup --N_epoch=102 --total_itr=8 --val_model_epoch=400 --fine_tune=yes --inp_itr_num=2 --num_workers=32 --dec_inp_type=dif_obs
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix              --N_batch=8 --val_model_epoch=400 --total_itr=7 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=FINE_TUNE_continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=32 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --N_epoch=102 --total_itr=8 --val_model_epoch=336 --fine_tune=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix            --N_batch=8 --val_model_epoch=360 --total_itr=7 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=FINE_TUNE_continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=32 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup --N_epoch=102 --total_itr=8 --val_model_epoch=336 --fine_tune=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES   --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr03_obsdif --N_batch=8 --val_model_epoch=368 --total_itr=7 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=FINE_TUNE_continuous_sequential_autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=32 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup --N_epoch=102 --total_itr=8 --val_model_epoch=392 --fine_tune=yes --inp_itr_num=2 --dec_inp_type=dif_obs
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cnt_sim_onlymlp_enc1dec0_woFix --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cnt_sim_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=352
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cnt_sim_encoder_enc3dec0_Fix --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc1dec0_woFix          --N_batch=8 --val_model_epoch=384 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc5dec5_Fix --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc5dec0_Fix --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr03_obsdif --N_batch=8 --val_model_epoch=368 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix              --N_batch=8 --val_model_epoch=352 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif_cls              --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_onlymlp_enc1dec0_woFix            --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif        --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix                     --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=376
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix_wpe                                --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rdn_sim_encoder_enc3dec0_Fix_dstmap                     --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif        --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix                   --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_encoder_enc3dec0_Fix              --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix                     --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif        --N_batch=8 --val_model_epoch=368 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_onlydecv2_Fix --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_onlydecv3_Fix --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc1dec0_woFix          --N_batch=8 --val_model_epoch=384 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif_latest --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif        --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=376
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif        --N_batch=8 --val_model_epoch=368 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif        --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif        --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif        --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix                   --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc1dec0_woFix          --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif        --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix                     --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_onlymlp_enc1dec0_woFix            --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_encoder_enc3dec0_Fix              --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix                   --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix                     --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336


# 無作為・同時・５回
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif_latest --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix                   --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix                     --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix                     --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif        --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif        --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif        --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix                   --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix                     --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix                     --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif        --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif        --N_batch=8 --val_model_epoch=368 --total_itr=10 --until_convergence=yes
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif        --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes

# 無作為・逐次・５回
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_onlymlp_enc1dec0_woFix            --N_batch=8 --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_encoder_enc3dec0_Fix              --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=376

# 連続的・逐次・５回
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc1dec0_woFix          --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_onlymlp_enc1dec0_woFix          --N_batch=8 --val_model_epoch=384 --total_itr=10 --until_convergence=yes --convergence_thr=30 --convergence_thr_shape=50
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_encoder_enc3dec0_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes --convergence_thr=30 --convergence_thr_shape=50
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_simultaneous_autoreg_enc3dec3_Fix            --N_batch=8 --val_model_epoch=336 --total_itr=10 --until_convergence=yes --convergence_thr=50 --convergence_thr_shape=50
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes --convergence_thr=30 --convergence_thr_shape=50
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/seq.txt --exp_version=continuous_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=392 --total_itr=10 --until_convergence=yes --convergence_thr=30 --convergence_thr_shape=50