# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt --exp_version=tes_scrach --N_batch=20
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach --N_batch=20 --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=20 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=20 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=20 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_finetune --N_batch=20 --backbone_training_strategy=finetune --lr_backbone=1.e-5
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_finetune --N_batch=20 --num_encoder_layers=2 --backbone_training_strategy=finetune --lr_backbone=1.e-5
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_resnet50   --N_batch=20 --backbone_training_strategy=scrach
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_catmapbefo --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2

# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers0 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=0
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers2 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers3 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers2 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers3 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers5 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers2 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --backbone_norms=with_out_norm
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers3 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=3