# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/mlp.txt     --exp_version=tes_scrach --N_batch=8                        --test_N_views=32 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/mlp.txt     --exp_version=tes_scrach --N_batch=8                        --test_N_views=32 --val_model_epoch=18
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/encoder.txt --exp_version=tes_scrach --N_batch=8 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/encoder.txt --exp_version=tes_scrach --N_batch=8 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=14

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_scrach --N_batch=5                        --test_N_views=32 --val_model_epoch=32
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach --N_batch=5 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=32
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif --val_model_epoch=32
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif --val_model_epoch=32
CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst --val_model_epoch=25
CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst --val_model_epoch=28
CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst --val_model_epoch=32