# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=3 --loss_timing=after_mean                                      --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=3 --transformer_model=pytorch --num_encoder_layers=2            --val_model_epoch=17
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers3        --N_batch=3 --transformer_model=pytorch --num_encoder_layers=3            --val_model_epoch=21

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcnn1_after_list0_randR05_inpOSMap_outObj.txt --exp_version=date0813    --N_batch=8 --loss_timing=before_mean --optim_num=1 --test_N_views=8 --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt   --exp_version=cnn01_after --N_batch=8 --loss_timing=before_mean --optim_num=1 --test_N_views=8 --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_fixed/baseline_list0fixed_randR05_inpOSMap_outObj.txt   --exp_version=cnn01_after --N_batch=8 --loss_timing=before_mean --optim_num=1 --test_N_views=8 --val_model_epoch=12

CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt   --exp_version=cnn01_after     --N_batch=20 --loss_timing=after_mean                           --optim_num=5 --test_N_views=32 --val_model_epoch=21
CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt   --exp_version=pytorch_layers3 --N_batch=20 --transformer_model=pytorch --num_encoder_layers=3 --optim_num=5 --test_N_views=32 --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=3 --loss_timing=after_mean                                      --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=3 --loss_timing=after_mean                                      --val_model_epoch=13
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0_fixed/transavg_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=20 --transformer_model=pytorch --num_encoder_layers=2 --val_model_epoch=17
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0_fixed/baseline_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=20 --loss_timing=after_mean                            --val_model_epoch=17
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0_fixed/transavg_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=20 --transformer_model=pytorch --num_encoder_layers=2 --val_model_epoch=17