# Encoderモデル
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_encoder           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80
# Autoregモデル
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_autoreg           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_autoreg           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_autoreg_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80
# MLPモデル
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_onlymlp           --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlymlp           --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlymlp_FINETUNE_ --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80
# Onlydec
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_onlydec           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlydec           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlydec_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes80
# # OnlyOnce
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlyonce           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=only_once --inp_itr_num=1 --positional_encoding_mode=yes --view_position=randn --view_selection=simultaneous --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlyonce_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=only_once --inp_itr_num=1 --positional_encoding_mode=yes --view_position=randn --view_selection=simultaneous --total_itr=10 --fine_tune=yes --val_model_epoch=80

# Tableの再開
# デバッグ中 CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=no --val_model_epoch=48
CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_autoreg_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=no --val_model_epoch=48
CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlymlp_FINETUNE_ --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing     --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=no --val_model_epoch=48
CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_onlydec_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --positional_encoding_mode=yes --fine_tune=no --val_model_epoch=48
CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_encoder           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7 --val_model_epoch=120
CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_autoreg           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7 --val_model_epoch=120
CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_onlymlp           --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing     --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7 --val_model_epoch=120
CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/rdn.txt --exp_version=rdn_onlydec           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --positional_encoding_mode=yes --total_itr=7 --val_model_epoch=120
# デバッグ中 CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder_FINETUNE_woSYM --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80 --sym_label_path=no # Debug
# デバッグ中 CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder_FINETUNE_ddf1e5 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80 --ddf_model_path=/home/yyoshitake/works/DeepSDF/project/DDF/lightning_logs/table/cat_depth_mae_normal_mae_seed0_normal001_lr00001/checkpoints/0000010000.ckpt # Debug
CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder_FINETUNE_Lr01Lc05 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80 --L_r=0.1 --L_c=0.5
CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/table/view5/seq.txt --exp_version=seq_encoder_FINETUNE_Lr01Lc01 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80 --L_r=0.1 --L_c=0.1