# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_onlydec305 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3 --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_onlydec205 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2 --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_autoreg_tau01img   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup  --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_tau01      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup  --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_onlydec305itr3 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3 --inp_itr_num=3 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle --train_data_dir=/d/workspace/yyoshitake/moving_camera/volumetric/tmp_2/results --val_data_dir=/d/workspace/yyoshitake/moving_camera/volumetric/tmp_2/results
CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_onlydec205itr3 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2 --inp_itr_num=3 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle --train_data_dir=/d/workspace/yyoshitake/moving_camera/volumetric/tmp_2/results --val_data_dir=/d/workspace/yyoshitake/moving_camera/volumetric/tmp_2/results
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec305 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3 --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=240
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec205 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2 --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=240
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_autoreg_tau01img   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup  --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=176
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_tau01      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup  --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=176
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec105 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec  --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=240
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_mmntau05   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=2 --main_layers_name=encoder --add_conf=momenenc --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=176
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_onlymlp_tau00    --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing  --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt