# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec105_FINETUNE_p2t10 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=no --val_model_epoch=424
CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=rndsim_encoder_onlydec105itr02           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --train_txtfile=dataset/sampled_path/chair/train/20221211065550_fultrain_randn_1000_10_2_all --val_data_list=/home/yyoshitake/works/DeepSDF/project/randn/val_scene.pickle --val_model_epoch=504


# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01padWope_FINETUNE_p2t10    --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1               --positional_encoding_mode=no  --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=no --val_model_epoch=96 # 340Epoまで
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01Wope_FINETUNE_p2t10       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1               --positional_encoding_mode=no  --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=no --val_model_epoch=96 # 340Epoまで
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec105Wope_FINETUNE_p2t10  --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2               --positional_encoding_mode=no  --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=160
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsimPG_encoder_onlydec105itr02Wpe           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec105itr02Wope            --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=no  --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes --val_model_epoch=272
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec105itr02                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=272


# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01padWope                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=no --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01padWope_FINETUNE_p2t10 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=no --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=160
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01Wope                   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=no --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01Wope_FINETUNE_p2t10    --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=no --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=160

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsimPG_autoreg_tau01imgWpe    --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes --val_model_epoch=192
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsimPG_encoder_tau01Wpe       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes --val_model_epoch=376
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsimPG_autoreg_tau01imgWope   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=no  --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes --val_model_epoch=248
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsimPG_encoder_tau01Wope      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=no  --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec105Wope                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=no --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=160
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec105Wope_FINETUNE_p2t10 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=no --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=160
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec105itr02Wope --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=no  --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --prg=yes

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec105                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec105_FINETUNE_p2t10 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=no --val_model_epoch=368
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_encoder_onlydec105itr02                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=272

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_onlymlp_tau00_FINETUNE_p2t10   --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all  --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle  --fine_tune=no --val_model_epoch=288
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=onlymlp_enc1dec0_woFix_wpe --N_batch=32 --main_layers_name=onlymlp --num_encoder_layers=1 --num_decoder_layers=0 --N_epoch=1000 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --train_txtfile=/home/yyoshitake/works/DeepSDF/project/dataset/sampled_path/chair/train/20221211065550_fultrain_randn_1000_10_2_all --val_data_list=/home/yyoshitake/works/DeepSDF/project/randn/val_scene.pickle --val_model_epoch=56


# # CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec305                       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec305_FINETUNE_p2t10       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_encoder_onlydec305                     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_encoder_onlydec305_FINETUNE_p2t10      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec205                       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec205_FINETUNE_p2t10       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_encoder_onlydec205                     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_encoder_onlydec205_FINETUNE_p2t10      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01pad                    --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01pad_FINETUNE_p2t10     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01                       --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01_FINETUNE_p2t10        --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_autoreg_tau01pad                  --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_autoreg_tau01pad_FINETUNE_p2t10   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_encoder_tau01                     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_encoder_tau01_FINETUNE_p2t10      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec205                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_onlydec305                --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3    --inp_itr_num=5 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01                     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_autoreg_tau01pad                  --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01                     --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_onlydec305 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec3 --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_onlydec205 --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec2 --inp_itr_num=5 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_autoreg_tau01img   --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup  --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_encoder_tau01      --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup  --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=/disks/local/yyoshitake/moving_camera/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle

# MLPのみ
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/tes.txt --exp_version=rndsim_onlymlp_tau00                    --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --val_model_epoch=176
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=bdrndsim_onlymlp_tau00                  --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221206152812_fultrain_randn_1000_0d7 --val_data_list=dataset/sampled_path/chair/val/20221206225143_val_randn_10_0d7.pickle --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_onlymlp_tau00                    --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_onlymlp_tau00_FINETUNE_p2t10     --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle  --fine_tune=no --val_model_epoch=184
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_onlymlp_tau00                  --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all  --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle  --itr_per_frame=1 --total_itr=5 --N_epoch=80
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=bdcntprg_onlymlp_tau00_FINETUNE_p2t10   --N_batch=16 --num_encoder_layers=1 --num_decoder_layers=0 --main_layers_name=onlymlp --add_conf=Nothing --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211082855_fultrain_continuous_1000_0d7_1_all  --val_data_list=dataset/sampled_path/chair/val/20221211084856_val_continuous_7_0d7_1_all.pickle  --fine_tune=no --val_model_epoch=248
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/txt.txt --exp_version=onlymlp_enc1dec0_woFix_wpe --N_batch=32 --main_layers_name=onlymlp --num_encoder_layers=1 --num_decoder_layers=0 --N_epoch=1000 --positional_encoding_mode=yes --train_instance_list_txt=instance_lists/paper_exp/fultrain.txt --train_txtfile=/home/yyoshitake/works/DeepSDF/project/dataset/sampled_path/chair/train/20221211065550_fultrain_randn_1000_10_2_all --val_data_list=/home/yyoshitake/works/DeepSDF/project/randn/val_scene.pickle
# 順次を一回で出した場合（書き換え：WrdOSMap入れる、WrdEst直接出す）
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/seq.txt --exp_version=cntprg_encoder_tau01_only_once --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --train_txtfile=dataset/sampled_path/chair/train/20221211035003_fultrain_continuous_1000_10_2_all  --val_data_list=dataset/sampled_path/chair/val/20221211061032_val_continuous_7_10_2_all.pickle --view_position=randn --view_selection=simultaneous --total_itr=1 --val_model_epoch=3112
