CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_wpe_estdif --N_batch=8 --val_model_epoch=360 --total_itr=10 --until_convergence=yes # 368
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=368 --total_itr=10 --until_convergence=yes --test_instance_list_txt=/home/yyoshitake/works/DeepSDF/project/randn/tes/randn_mini.pickle # 368
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix --N_batch=8 --val_model_epoch=400 --total_itr=10 --until_convergence=yes  --test_instance_list_txt=/home/yyoshitake/works/DeepSDF/project/randn/tes/randn_mini.pickle # 368
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif --N_batch=8 --val_model_epoch=400 # 368
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --val_model_epoch=368 # 368
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix              --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_wpe_estdif --N_batch=8 --val_model_epoch=360 --total_itr=10 --test_instance_list_txt=/home/yyoshitake/works/DeepSDF/project/randn/tes/randn_mini.pickle
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif     --N_batch=8 --val_model_epoch=400 --total_itr=10 --test_instance_list_txt=/home/yyoshitake/works/DeepSDF/project/randn/tes/randn_mini.pickle
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr03_obsdif     --N_batch=8 --val_model_epoch=360 --total_itr=10 --test_instance_list_txt=/home/yyoshitake/works/DeepSDF/project/randn/tes/randn_mini.pickle
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_dstmap_estdif --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=continuous_simultaneous_onlymlp_enc1dec0_woFix --N_batch=8 --val_model_epoch=320
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_wpe_estdif --N_batch=8 --val_model_epoch=392 # 328
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_wpe_estdif --N_batch=8 --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --view_selection=sequential --val_model_epoch=376
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_encoder_enc3dec0_Fix --N_batch=8 --view_selection=sequential --val_model_epoch=384
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=randn_sequential_autoreg_enc3dec3_Fix_itr01_estdif --N_batch=8 --view_selection=sequential --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsestdif --N_batch=8 --val_model_epoch=344
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_estdif --N_batch=8 --val_model_epoch=360

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr03_obsdif    --N_batch=8 --val_model_epoch=320 # 368
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_obsdif    --N_batch=8 --val_model_epoch=368 # 320
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr01_obsestdif --N_batch=8 --val_model_epoch=360 # 320
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix_itr02_attnmask  --N_batch=8 --val_model_epoch=328 # 360
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_onlydecv2_Fix --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_onlydecv3_Fix --N_batch=8 --val_model_epoch=368

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc1dec0_woFix --N_batch=8 --val_model_epoch=360
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=onlymlp_enc3dec0_woFix --N_batch=8 --val_model_epoch=384 # 328
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_woFix --N_batch=8 --val_model_epoch=328
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc3dec0_Fix   --N_batch=8 --val_model_epoch=400
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc5dec0_woFix --N_batch=8 --val_model_epoch=352
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=encoder_enc5dec0_Fix   --N_batch=8 --val_model_epoch=376 # 336
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc3dec3_Fix   --N_batch=8 --val_model_epoch=296 # 352
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TES --config=configs/paper_exp/chair/view5/tes.txt --exp_version=autoreg_enc5dec5_Fix   --N_batch=8 --val_model_epoch=352