# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_autoreg --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_autoreg --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_autoreg_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80
# # Encoder
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_encoder --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_encoder --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80
# # Decoder
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_onlydec --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --total_itr=7
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_onlydec --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_encoder --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80 --val_model_epoch=56
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_encoder_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup --inp_itr_num=1 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_onlydec --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --prg=yes --cnt_prg_step=80 --N_epoch=80 --val_model_epoch=56
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_onlydec_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec --inp_itr_num=2 --positional_encoding_mode=yes --fine_tune=yes --val_model_epoch=80

# Canimet 無作為 WoPE
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_autoreg_prgWope --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=no --prg=yes
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_encoder_prgWope --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --total_itr=7 --positional_encoding_mode=no --prg=yes
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_onlydec_prgWope --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --total_itr=7 --positional_encoding_mode=no --prg=yes

# Canimet 連続的 WoPE
CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_autoreg_prgWope           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=no --prg=yes --cnt_prg_step=160 --N_epoch=160
CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_autoreg_prgWope_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=3 --main_layers_name=autoreg --add_conf=T_Fixup_Pad --inp_itr_num=1 --positional_encoding_mode=no --fine_tune=yes --val_model_epoch=160
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_onlydec_prgWope           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --positional_encoding_mode=no --prg=yes --cnt_prg_step=160 --N_epoch=160
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_onlydec_prgWope_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=onlydec     --inp_itr_num=2 --positional_encoding_mode=no --fine_tune=yes --val_model_epoch=160

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=REVAL --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_autoreg --N_batch=16 --val_data_list=/home/yyoshitake/works/DeepSDF/project/dataset/sampled_path/cabinet/val/20230110151503_val_randn_32_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=REVAL --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_encoder --N_batch=16 --val_data_list=/home/yyoshitake/works/DeepSDF/project/dataset/sampled_path/cabinet/val/20230110151503_val_randn_32_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=REVAL --config=configs/paper_exp/cabinet/view5/rdn.txt --exp_version=rdn_onlydec --N_batch=16 --val_data_list=/home/yyoshitake/works/DeepSDF/project/dataset/sampled_path/cabinet/val/20230110151503_val_randn_32_10_2_all.pickle
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_encoder_prgWope           --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=no --prg=yes --cnt_prg_step=160 --N_epoch=160
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/cabinet/view5/seq.txt --exp_version=seq_encoder_prgWope_FINETUNE_ --N_batch=16 --num_encoder_layers=3 --num_decoder_layers=0 --main_layers_name=encoder --add_conf=T_Fixup     --inp_itr_num=1 --positional_encoding_mode=no --fine_tune=yes --val_model_epoch=160