CUDA_VISIBLE_DEVICES=0 python val_adam.py --config=configs/initnet_list0.txt --N_batch=1 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --grad_optim_max=50 --shape_code_reg=0.01
CUDA_VISIBLE_DEVICES=3 python val_adam.py --config=configs/initnet_list0.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --grad_optim_max=100
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/initnet_list0.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000700.ckpt --model_mode=only_init
CUDA_VISIBLE_DEVICES=5 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/dfnet_list0.txt --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=all
CUDA_VISIBLE_DEVICES=6 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt
CUDA_VISIBLE_DEVICES=7 python train_ori.py --config=configs/dfnet_list0.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000700.ckpt
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/initnet_list2.txt --N_batch=50 --val_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000300.ckpt --model_mode=only_init
CUDA_VISIBLE_DEVICES=1 python train_ini.py --config=configs/initnet_list0.txt --frame_sequence_num=5 --exp_version=date0705 --expname=DeepTaR/chair/initnet_list0
CUDA_VISIBLE_DEVICES=7 python train_ini.py --config=configs/initnet_list2.txt --frame_sequence_num=5 --exp_version=date0705 --expname=DeepTaR/chair/initnet_list2
CUDA_VISIBLE_DEVICES=1 python val_adam.py --config=configs/initnet_list0.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt
CUDA_VISIBLE_DEVICES=2 python val_adam.py --config=configs/initnet_list2.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000200.ckpt
CUDA_VISIBLE_DEVICES=5 python train_ori.py --config=configs/dfnet_list0.txt --exp_version=date0707
CUDA_VISIBLE_DEVICES=0 python train_ori.py --config=configs/dfnet_list2.txt --exp_version=date0707
CUDA_VISIBLE_DEVICES=4 python train_ori.py --config=configs/dfnet_list0_randR05.txt --exp_version=date0707
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/dfnet_list0.txt --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000700.ckpt --optim_mode=optimall
CUDA_VISIBLE_DEVICES=3 python train_ori.py --config=configs/dfnet_list0.txt --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=all
CUDA_VISIBLE_DEVICES=5 python train_ori.py --config=configs/dfnet_list0.txt --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=1 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=optimall
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=all
CUDA_VISIBLE_DEVICES=4 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=0 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=optimall
CUDA_VISIBLE_DEVICES=1 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=3 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=0 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=20 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=optimall
CUDA_VISIBLE_DEVICES=1 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=20 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000200.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0707/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=1 python val_adam.py --config=configs/initnet_list0.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --grad_optim_max=50 --shape_code_reg=0.01
CUDA_VISIBLE_DEVICES=0 python val_adam.py --config=configs/initnet_list2.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --grad_optim_max=50 --shape_code_reg=0.01
CUDA_VISIBLE_DEVICES=0 python val_adam.py --config=configs/initnet_list2.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --grad_optim_max=50 --shape_code_reg=0.01
CUDA_VISIBLE_DEVICES=1 python val_adam.py --config=configs/initnet_list0.txt --N_batch=5 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --grad_optim_max=50 --shape_code_reg=0.01
CUDA_VISIBLE_DEVICES=0 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=1 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_depth_sample_randR05_date0713/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=2,3,4 python train_ori.py --config=configs/dfnet_list0_depth_full_randR05.txt --exp_version=date0713
CUDA_VISIBLE_DEVICES=5 python train_ori.py --config=configs/dfnet_list0_depth_clop_randR05.txt --exp_version=date0713
CUDA_VISIBLE_DEVICES=7 python train_ori.py --config=configs/dfnet_list0_depth_sample_randR05.txt --exp_version=date0713
CUDA_VISIBLE_DEVICES=2 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=10 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_depth_clop_randR05_date0713/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=1 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=10 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_depth_full_randR05_date0713/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=0 python train_ori.py --config=configs/dfnet_list0_randR05.txt --N_batch=10 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_depth_sample_randR05_date0713/checkpoints/0000000700.ckpt --optim_mode=progressive --init_mode=single
CUDA_VISIBLE_DEVICES=5 python train_ori.py --config=configs/dfnet_list0_randR05.txt --exp_version=tes --N_batch=2 --integrate_mode=transformer_v1
# CUDA_VISIBLE_DEVICES=3,4 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_trans_avgv2.txt  --exp_version=date0719
# CUDA_VISIBLE_DEVICES=5,7 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_trans_avgv2.txt  --exp_version=date0719
# CUDA_VISIBLE_DEVICES=3,4,5,6,7 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_depth_raw_randR05.txt --exp_version=date0718Ld01 --L_d=0.1 # --depth_error_mode=full
# CUDA_VISIBLE_DEVICES=3,4,5,6,7 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_depth_raw_randR05.txt --exp_version=date0718 # --depth_error_mode=full
CUDA_VISIBLE_DEVICES=0,1 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_trans_mlpQ.txt --exp_version=3layer_date0719
# CUDA_VISIBLE_DEVICES=2,3 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_trans_avg.txt  --exp_version=date0718
# CUDA_VISIBLE_DEVICES=4,5 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05.txt            --exp_version=date0718
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL --config=configs/dfnet_list0_randR05_trans_mlpQ.txt --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_trans_mlpQ_date0717/checkpoints/0000000700.ckpt --optim_mode=optimall
CUDA_VISIBLE_DEVICES=2 python train_ori.py --code_mode=VAL --config=configs/dfnet_list0_randR05_trans_avg.txt  --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_trans_avgv2_date0719/checkpoints/0000000500.ckpt  --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=2 python train_ori.py --code_mode=VAL --config=configs/dfnet_list0_randR05.txt            --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0717/checkpoints/0000000700.ckpt            --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=3 python train_ori.py --code_mode=VAL --config=configs/dfnet_list0_randR05_trans_mlpQ.txt --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_trans_mlpQ_date0717/checkpoints/0000000600.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=4 python train_ori.py --code_mode=VAL --config=configs/dfnet_list0_randR05_trans_avg.txt  --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_trans_avg_date0717/checkpoints/0000000600.ckpt  --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=5 python train_ori.py --code_mode=VAL --config=configs/dfnet_list0_randR05.txt            --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_date0717/checkpoints/0000000600.ckpt            --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=7 python train_ori.py --code_mode=VAL --config=configs/dfnet_list2_randR05_trans_avg.txt  --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_trans_avg_date0718/checkpoints/0000000500.ckpt  --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=2 python train_ori.py --code_mode=VAL --config=configs/dfnet_list2_randR05.txt            --N_batch=2 --val_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_date0718/checkpoints/0000000500.ckpt            --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=2 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_sha.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=3 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_sha_zero_atten.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=4 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_sha_separate_atten.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=5 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_mha_avg.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=6 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_mha_avg_learned_weighted.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=7 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_origin_after.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=8 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_origin_before.txt  --exp_version=date0721 --N_batch=10
# CUDA_VISIBLE_DEVICES=9 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_sha_nn_liner.txt  --exp_version=date0723 --N_batch=10




# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha.txt                      --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_date0721/checkpoints/0000000600.ckpt                      --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_zero_atten.txt           --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_zero_atten_date0721/checkpoints/0000000600.ckpt           --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_separate_atten.txt       --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_separate_atten/checkpoints/0000000600.ckpt                --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg.txt                  --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_date0721/checkpoints/0000000600.ckpt                  --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_learned_weighted.txt --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_learned_weighted_date0721/checkpoints/0000000600.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_after.txt             --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_after_date0721/checkpoints/0000000600.ckpt             --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_before.txt            --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_before_date0721/checkpoints/0000000600.ckpt            --optim_mode=optimall


CUDA_VISIBLE_DEVICES=2 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha.txt                      --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_date0721/checkpoints/0000000700.ckpt                      --optim_mode=optimall
CUDA_VISIBLE_DEVICES=3 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_zero_atten.txt           --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_zero_atten_date0721/checkpoints/0000000700.ckpt           --optim_mode=optimall
CUDA_VISIBLE_DEVICES=4 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_separate_atten.txt       --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_separate_atten/checkpoints/0000000700.ckpt                --optim_mode=optimall
CUDA_VISIBLE_DEVICES=5 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg.txt                  --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_date0721/checkpoints/0000000700.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=6 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_learned_weighted.txt --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_learned_weighted_date0721/checkpoints/0000000700.ckpt --optim_mode=optimall
CUDA_VISIBLE_DEVICES=7 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_after.txt             --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_after_date0721/checkpoints/0000000700.ckpt             --optim_mode=optimall
CUDA_VISIBLE_DEVICES=8 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_before.txt            --N_batch=12 --val_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_before_date0721/checkpoints/0000000700.ckpt            --optim_mode=optimall
CUDA_VISIBLE_DEVICES=1 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg.txt                  --N_batch=2 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_date0721/checkpoints/0000000500.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=1 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg.txt                  --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_date0721/checkpoints/0000000300.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=1 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg.txt                  --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_date0721/checkpoints/0000000400.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_after.txt             --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_after_date0721/checkpoints/0000000200.ckpt             --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_after.txt             --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_after_date0721/checkpoints/0000000300.ckpt             --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_origin_after.txt             --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_origin_after_date0721/checkpoints/0000000400.ckpt             --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_learned_weighted.txt                      --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_learned_weighted_date0721/checkpoints/0000000600.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_learned_weighted.txt                      --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_learned_weighted_date0721/checkpoints/0000000400.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_nn_liner.txt             --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_nn_liner_date0723/checkpoints/0000000500.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha.txt                      --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_date0721/checkpoints/0000000600.ckpt                  --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha.txt                      --N_batch=20 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_date0721/checkpoints/0000000400.ckpt                  --optim_mode=optimall

# CUDA_VISIBLE_DEVICES=1 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_before.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_before_date0723/checkpoints/0000000400.ckpt                --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=1 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_before.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_before_date0723/checkpoints/0000000500.ckpt                --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=1 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_before.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_before_date0723/checkpoints/0000000600.ckpt                --optim_mode=optimall

CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_before.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_before_date0723/checkpoints/0000000400.ckpt                --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_before.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_before_date0723/checkpoints/0000000300.ckpt                --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_mha_avg_before.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_mha_avg_before_date0723/checkpoints/0000000600.ckpt                --optim_mode=optimall

CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_separate_atten.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_separate_atten_date0721/checkpoints/0000000300.ckpt                --optim_mode=optimall
CUDA_VISIBLE_DEVICES=0 python train_ori.py --code_mode=VAL   --config=configs/dfnet_list0_randR05_sha_separate_atten.txt       --N_batch=12 --test_instance_list_txt=instance_lists/kmean/kmeans0_test_list.txt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list0_date0705/checkpoints/0000000500.ckpt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list0_randR05_sha_separate_atten_date0721/checkpoints/0000000400.ckpt                --optim_mode=optimall

# CUDA_VISIBLE_DEVICES=1 python train_ori.py --N_batch=12 --code_mode=VAL --config=configs/dfnet_list2_randR05_sha.txt --test_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_sha_date0723/checkpoints/0000000500.ckpt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=1 python train_ori.py --N_batch=12 --code_mode=VAL --config=configs/dfnet_list2_randR05_mha_avg.txt --test_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_mha_avg_date0723/checkpoints/0000000500.ckpt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=1 python train_ori.py --N_batch=12 --code_mode=VAL --config=configs/dfnet_list2_randR05_origin_after.txt --test_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_origin_after_date0723/checkpoints/0000000500.ckpt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --N_batch=12 --code_mode=VAL --config=configs/dfnet_list2_randR05_sha.txt --test_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_sha_date0723/checkpoints/0000000100.ckpt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --N_batch=12 --code_mode=VAL --config=configs/dfnet_list2_randR05_mha_avg.txt --test_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_mha_avg_date0723/checkpoints/0000000100.ckpt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --optim_mode=optimall
# CUDA_VISIBLE_DEVICES=0 python train_ori.py --N_batch=12 --code_mode=VAL --config=configs/dfnet_list2_randR05_origin_after.txt --test_instance_list_txt=instance_lists/kmean/kmeans2_test_list.txt --model_ckpt_path=lightning_logs/DeepTaR/chair/dfnet_list2_randR05_origin_after_date0723/checkpoints/0000000100.ckpt --initnet_ckpt_path=lightning_logs/DeepTaR/chair/initnet_list2_date0705/checkpoints/0000000500.ckpt --optim_mode=optimall

# CUDA_VISIBLE_DEVICES=6 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_mha_avg_learned_weighted.txt  --exp_version=date0723 --N_batch=2
# CUDA_VISIBLE_DEVICES=2 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_sha_before.txt  --exp_version=date0723 --N_batch=10
# CUDA_VISIBLE_DEVICES=3 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list0_randR05_mha_avg_bfore.txt  --exp_version=date0723 --N_batch=10
# CUDA_VISIBLE_DEVICES=4 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_sha.txt  --exp_version=date0723 --N_batch=10
# CUDA_VISIBLE_DEVICES=5 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_mha_avg.txt  --exp_version=date0723 --N_batch=10
# CUDA_VISIBLE_DEVICES=6 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_mha_avg_learned_weighted.txt  --exp_version=date0723 --N_batch=10
CUDA_VISIBLE_DEVICES=7 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_origin_after.txt  --exp_version=tes --N_batch=12
# CUDA_VISIBLE_DEVICES=8 python train_ori.py --code_mode=TRAIN --config=configs/dfnet_list2_randR05_origin_before.txt  --exp_version=date0723 --N_batch=10

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_origin_after_list0_randR05_inpDepth_outImg.txt         --exp_version=date0810 --N_batch=8
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_origin_after_list0_randR05_inpDepth_outObj.txt         --exp_version=date0810 --N_batch=8
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_origin_after_list0_randR05_inpOSMap_outObj.txt         --exp_version=date0810 --N_batch=8 --val_model_epoch=10
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peAdd.txt --exp_version=date0810 --N_batch=8
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peCat.txt --exp_version=date0810 --N_batch=8
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt       --exp_version=date0810 --N_batch=8
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpOSMap_outObj_peAdd.txt --exp_version=date0810 --N_batch=8
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt        --exp_version=date0813 --N_batch=8 --val_model_epoch=3
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcnn1_after_list0_randR05_inpOSMap_outObj.txt       --exp_version=date0813 --N_batch=8
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcnn2_after_list0_randR05_inpOSMap_outObj.txt       --exp_version=date0813 --N_batch=8
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt        --exp_version=batchseqhidden --N_batch=8
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt        --exp_version=detach --N_batch=8
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt        --exp_version=layernorm --N_batch=8
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt        --exp_version=onlymean --N_batch=8
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt        --exp_version=MLP --N_batch=8
CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=0layers --N_batch=10 --num_encoder_layers=0

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=1layers --N_batch=10 --num_encoder_layers=1
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=2layers --N_batch=10 --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=3layers --N_batch=10 --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=6layers --N_batch=10 --num_encoder_layers=6
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=1layers_detach --N_batch=8 --num_encoder_layers=1
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=2layers_dff1024_dh256  --N_batch=10 --num_encoder_layers=2 --dim_feedforward=1024 --hidden_dim=256
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=2layers_wupLr_step4000 --N_batch=10 --num_encoder_layers=2 --lr=-1
CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=2layers_nondropout     --N_batch=10 --num_encoder_layers=2 --dropout=0.0

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=4layers                --N_batch=10 --num_encoder_layers=4
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=5layers                --N_batch=10 --num_encoder_layers=5
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peAdd.txt --exp_version=3layers_nonPe --N_batch=10  --num_encoder_layers=3 --positional_encoding_mode=non
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=1layers                --N_batch=10 --num_encoder_layers=1
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=2layers                --N_batch=10 --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=3layers                --N_batch=10 --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=6layers                --N_batch=10 --num_encoder_layers=6
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=6layers_wupLr_step4000 --N_batch=10 --num_encoder_layers=6 --lr=-1
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpOSMap_outObj.txt --exp_version=1layers_split_wPe           --N_batch=10 --num_encoder_layers=1 --split_into_patch=wPe
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpOSMap_outObj.txt --exp_version=3layers_split_wPe           --N_batch=10 --num_encoder_layers=3 --split_into_patch=wPe
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpOSMap_outObj.txt --exp_version=3layers_split_woPe           --N_batch=10 --num_encoder_layers=3 --split_into_patch=woPe

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peAdd.txt --exp_version=3layers --num_encoder_layers=3 --N_batch=10
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peCat.txt --exp_version=3layers --num_encoder_layers=3 --N_batch=10
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpOSMap_outObj_peAdd.txt --exp_version=3layers --num_encoder_layers=3 --N_batch=10

# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=1layers --N_batch=2 --num_encoder_layers=1 --init_net_epoch=300 --val_model_epoch=10
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=2layers --N_batch=2 --num_encoder_layers=2 --init_net_epoch=300 --val_model_epoch=10
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=3layers --N_batch=2 --num_encoder_layers=3 --init_net_epoch=300 --val_model_epoch=10
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcnn1_after_list0_randR05_inpOSMap_outObj.txt --exp_version=date0813 --N_batch=2 --num_encoder_layers=0 --init_net_epoch=300 --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcnn2_after_list0_randR05_inpOSMap_outObj.txt --exp_version=date0813 --N_batch=2 --num_encoder_layers=0 --init_net_epoch=300 --val_model_epoch=10
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=1layers --N_batch=2 --num_encoder_layers=1 --init_net_epoch=300 --val_model_epoch=13
CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=2layers --N_batch=2 --num_encoder_layers=2 --init_net_epoch=300 --val_model_epoch=13
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=3layers --N_batch=2 --num_encoder_layers=3 --init_net_epoch=300 --val_model_epoch=13
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcnn1_after_list0_randR05_inpOSMap_outObj.txt --exp_version=date0813 --N_batch=2 --num_encoder_layers=0 --init_net_epoch=300 --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcnn2_after_list0_randR05_inpOSMap_outObj.txt --exp_version=date0813 --N_batch=2 --num_encoder_layers=0 --init_net_epoch=300 --val_model_epoch=14
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transavg_after_list0_randR05_inpOSMap_outObj.txt --exp_version=1layers --N_batch=2 --num_encoder_layers=1 --init_net_epoch=300 --val_model_epoch=15

# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=1layers --N_batch=2 --num_encoder_layers=1 --init_net_epoch=300 --val_model_epoch=11
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=2layers --N_batch=2 --num_encoder_layers=2 --init_net_epoch=300 --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=3layers --N_batch=2 --num_encoder_layers=3 --init_net_epoch=300 --val_model_epoch=8
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=3layers --N_batch=2 --num_encoder_layers=3 --init_net_epoch=300 --val_model_epoch=13
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj.txt --exp_version=6layers --N_batch=2 --num_encoder_layers=6 --init_net_epoch=300 --val_model_epoch=10

# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peAdd.txt --exp_version=3layers --num_encoder_layers=3 --N_batch=2 --init_net_epoch=300 --val_model_epoch=11
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpDepth_outObj_peCat.txt --exp_version=3layers --num_encoder_layers=3 --N_batch=2 --init_net_epoch=300 --val_model_epoch=13
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcls_after_list0_randR05_inpOSMap_outObj_peAdd.txt --exp_version=3layers --num_encoder_layers=3 --N_batch=2 --init_net_epoch=300 --val_model_epoch=12

# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=3 --loss_timing=after_mean                                      --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=3 --transformer_model=pytorch --num_encoder_layers=2            --val_model_epoch=17
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers3        --N_batch=3 --transformer_model=pytorch --num_encoder_layers=3            --val_model_epoch=21

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0/dfnet_transcnn1_after_list0_randR05_inpOSMap_outObj.txt --exp_version=date0813    --N_batch=8 --loss_timing=before_mean --optim_num=1 --test_N_views=8 --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt   --exp_version=cnn01_after --N_batch=8 --loss_timing=before_mean --optim_num=1 --test_N_views=8 --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_fixed/baseline_list0fixed_randR05_inpOSMap_outObj.txt   --exp_version=cnn01_after --N_batch=8 --loss_timing=before_mean --optim_num=1 --test_N_views=8 --val_model_epoch=12

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt   --exp_version=cnn01_after     --N_batch=20 --loss_timing=after_mean                           --optim_num=5 --test_N_views=32 --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt   --exp_version=pytorch_layers3 --N_batch=1 --transformer_model=pytorch --num_encoder_layers=3 --optim_num=5 --test_N_views=32 --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=3 --loss_timing=after_mean                                      --val_model_epoch=12
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=3 --loss_timing=after_mean                                      --val_model_epoch=13
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0_fixed/transavg_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=20 --transformer_model=pytorch --num_encoder_layers=2 --val_model_epoch=17
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0_fixed/baseline_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=20 --loss_timing=after_mean                            --val_model_epoch=17
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0_fixed/transavg_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=1 --transformer_model=pytorch --num_encoder_layers=2 --optim_num=5 --val_model_epoch=17


# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=20 --loss_timing=after_mean
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0_randn/baseline_list0randn_randR05_inpOSMap_outObj.txt --exp_version=cnn01_before           --N_batch=20 --loss_timing=before_mean
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=20 --transformer_model=pytorch --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers3        --N_batch=20 --transformer_model=pytorch --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2_lr5e-5 --N_batch=20 --transformer_model=pytorch --num_encoder_layers=2 --lr=5.e-5
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0_fixed/baseline_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=cnn01_after            --N_batch=20 --loss_timing=after_mean
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0_fixed/baseline_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=cnn01_before           --N_batch=20 --loss_timing=before_mean
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0_fixed/transavg_list0fixed_randR05_inpOSMap_outObj.txt --exp_version=pytorch_layers2        --N_batch=20 --transformer_model=pytorch --num_encoder_layers=2

# ＊＊＊ CCUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=meanonly_nonDropout        --N_batch=20 --num_encoder_layers=0
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=mhaonly_nonDropout         --N_batch=20 --num_encoder_layers=0
# ＊＊＊  CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=nonNorm_nonDropout_layers1 --N_batch=20 --num_encoder_layers=1
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=nonNorm_nonDropout_layers2 --N_batch=20 --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=/home/yyoshitake/works/DeepSDF/project/configs/list_0/randn/resolution256/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=nonNorm_01Dropout_layers2  --N_batch=20 --num_encoder_layers=2
# ＊＊＊ CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=nonNorm_nonDropout_layers3 --N_batch=20 --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0_randn/transavg_list0randn_randR05_inpOSMap_outObj.txt --exp_version=nonNorm_01Dropout_layers3  --N_batch=20 --num_encoder_layers=3

CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/baseconf.txt --expname=DeepTaR/chair/encoder --N_batch=2 --main_layers_name=encoder_model --num_encoder_layers=2 --optim_num=5 --test_N_views=32 --val_model_epoch=1
CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/autoreg.txt --exp_version=nonNorm_01Dropout_layerse2d1 --N_batch=2 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=5

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=nonNorm_01Dropout_layers3 --N_batch=20 --num_encoder_layers=3
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt --exp_version=hid1024_01Dropout_layers3 --N_batch=20
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=nonNorm_01Dropout_layerse2d1 --N_batch=20 --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt --exp_version=tes_scrach --N_batch=20
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach --N_batch=20 --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=20 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=20 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=20 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_finetune --N_batch=20 --backbone_training_strategy=finetune --lr_backbone=1.e-5
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_finetune --N_batch=20 --num_encoder_layers=2 --backbone_training_strategy=finetune --lr_backbone=1.e-5
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_resnet50   --N_batch=20 --backbone_training_strategy=scrach
# CUDA_VISIBLE_DEVICES=9 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_catmapbefo --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/mlp.txt     --exp_version=tes_scrach --N_batch=8                        --test_N_views=32 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/encoder.txt --exp_version=tes_scrach --N_batch=8 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/mlp.txt     --exp_version=tes_scrach --N_batch=8                        --test_N_views=32 --val_model_epoch=18
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/encoder.txt --exp_version=tes_scrach --N_batch=8 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=14

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_scrach --N_batch=5                        --test_N_views=32 --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach --N_batch=5 --num_encoder_layers=2 --test_N_views=32 --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach01 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinEst_decoutDif --val_model_epoch=32
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach02 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutDif --val_model_epoch=32
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=tes_scrach03 --N_batch=5 --num_encoder_layers=2 --num_decoder_layers=1 --backbone_training_strategy=scrach --optnet_InOut_type=encinObs_decinDif_decoutEst --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers2  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers2  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers5  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=5
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/autoreg.txt --exp_version=scrach_enc2dec2 --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2 --num_decoder_layers=2
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/autoreg.txt --exp_version=scrach_enc5dec5growth --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/autoreg.txt --exp_version=scrach_enc5dec5growth --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers2  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --val_model_epoch=21
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers2_Ls1e1  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --val_model_epoch=26
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers2_Ls1e1  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --val_model_epoch=26
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_oldenc2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --main_layers_name=cnn_only_1 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_oldenc2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --main_layers_name=encoder --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc2dec2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --num_decoder_layers=2 --val_model_epoch=28
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22    --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22 --val_model_epoch=28

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_layers2_Ls1e1  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2 --L_s=1e1
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers2_Ls1e1  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2 --L_s=1e1
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=scrach_oldenc2  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2 --main_layers_name=cnn_only_1
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_oldenc2  --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=2 --main_layers_name=encoder
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5  --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc2dec2 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --num_decoder_layers=2
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22    --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/autoreg.txt --exp_version=scrach_enc5dec5_fixNorm --N_batch=64 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=fix_norm
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_0923 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=Nothing

# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=oldenc2_res18_Ls1e1 --N_batch=64 --backbone_training_strategy=scrach --L_s=1e1 --main_layers_name=cnn_only_1
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=oldenc2_res18only_Ls1e1 --N_batch=64 --backbone_training_strategy=scrach --L_s=1e1 --main_layers_name=cnn_only_1
CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=oldenc2_res18_Ls1e1_tes --N_batch=5 --backbone_training_strategy=scrach --L_s=1e1 --main_layers_name=encoder
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_fixNorm2 --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=fix_norm
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22v2  --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22v2

# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/mlp.txt     --exp_version=oldenc2_res18_Ls1e1  --N_batch=5 --backbone_training_strategy=scrach --main_layers_name=cnn_only_1 --val_model_epoch=21
# # CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=oldenc2_res18_Ls1e1  --N_batch=5 --backbone_training_strategy=scrach --main_layers_name=encoder --val_model_epoch=21
# # CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/old_data/encoder.txt --exp_version=scrach_layers2_Ls1e1 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --val_model_epoch=21


# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_scrach      --N_batch=5 --backbone_training_strategy=scrach                                               --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_scrach      --N_batch=5 --backbone_training_strategy=scrach                                               --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/mlp.txt     --exp_version=tes_scrach      --N_batch=5 --backbone_training_strategy=scrach                                               --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach      --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2                        --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach      --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2                        --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=tes_scrach      --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2                        --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5                        --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5                        --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5                        --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc2dec2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --num_decoder_layers=2 --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc2dec2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --num_decoder_layers=2 --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc2dec2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --num_decoder_layers=2 --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22    --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22       --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22    --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22       --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22    --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22       --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_fixNorm2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=fix_norm    --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_fixNorm2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=fix_norm    --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_fixNorm2 --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=fix_norm    --val_model_epoch=32

# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22v2  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22v2     --val_model_epoch=15
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22v2  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22v2     --val_model_epoch=25
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_exp22v2  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=exp22v2     --val_model_epoch=32



# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_noFixUp01       --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --dropout=0.1 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5_FixUp01          --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydec                  --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydec
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydecv2                --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydecv2
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01_endcall --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --dropout=0.1 --add_conf=T_Fixup --optnet_InOut_type=en_dc_all
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01_dcall   --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --dropout=0.1 --add_conf=T_Fixup --optnet_InOut_type=dc_all
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers2_FixUp01          --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=T_Fixup
CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydecv3                --N_batch=20 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydecv2

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01         --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01         --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5_FixUp01          --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=T_Fixup --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers5_FixUp01          --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=T_Fixup --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp05         --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp05         --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydec                  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydec --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydec                  --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydec --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydecv2                --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydecv2 --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=4 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_onlydecv2                --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --add_conf=onlydecv2 --val_model_epoch=28

# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers2_FixUp01          --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=T_Fixup --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/encoder.txt --exp_version=scrach_layers2_FixUp01          --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=2 --add_conf=T_Fixup --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01_endcall --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --optnet_InOut_type=en_dc_all --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01_endcall --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --optnet_InOut_type=en_dc_all --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01_dcall   --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --optnet_InOut_type=dc_all --val_model_epoch=16
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=VAL --config=configs/list_0/randn/resolution128/new_data/autoreg.txt --exp_version=scrach_enc5dec5_FixUp01_dcall   --N_batch=5 --backbone_training_strategy=scrach --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup --optnet_InOut_type=dc_all --val_model_epoch=20

# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=layers2_noFixUp01  --N_batch=32 --num_encoder_layers=2 --num_decoder_layers=0 --add_conf=Nothing
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=layers5_noFixUp01  --N_batch=32 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=Nothing
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/mlp.txt --exp_version=onlymlp_noFixUp01      --N_batch=32 --num_encoder_layers=2 --num_decoder_layers=0 --add_conf=Nothing
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=exp22v2_noFixUp01  --N_batch=32 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=exp22v2
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/autoreg.txt --exp_version=enc5dec5_FixUp01   --N_batch=32 --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=onlydecv1_FixUp01  --N_batch=32 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=onlydec
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=onlydecv2_FixUp01  --N_batch=32 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=onlydecv2
# CUDA_VISIBLE_DEVICES=8 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=onlydecv3_FixUp01  --N_batch=32 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=onlydecv3
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=tes --N_batch=3 --num_encoder_layers=2 --num_decoder_layers=0 --add_conf=Nothing
# CUDA_VISIBLE_DEVICES=1 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=tes --N_batch=3 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=Nothing
# CUDA_VISIBLE_DEVICES=2 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/mlp.txt     --exp_version=tes --N_batch=3 --num_encoder_layers=2 --num_decoder_layers=0 --add_conf=Nothing
# CUDA_VISIBLE_DEVICES=3 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=tes --N_batch=4 --num_encoder_layers=1 --num_decoder_layers=0 --add_conf=exp22v2
# CUDA_VISIBLE_DEVICES=5 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/autoreg.txt --exp_version=tes --N_batch=3 --num_encoder_layers=5 --num_decoder_layers=5 --add_conf=T_Fixup
# CUDA_VISIBLE_DEVICES=6 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=tes --N_batch=3 --num_encoder_layers=5 --num_decoder_layers=0 --add_conf=onlydec
# CUDA_VISIBLE_DEVICES=7 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=tes --N_batch=3 --num_encoder_layers=1 --num_decoder_layers=0 --add_conf=onlydecv2
# CUDA_VISIBLE_DEVICES=0 python train.py --code_mode=TRAIN --config=configs/paper_exp/chair/view5/encoder.txt --exp_version=tes --N_batch=3 --num_encoder_layers=1 --num_decoder_layers=0 --add_conf=onlydecv3